#=================================================
# Description: OpenWrt Autobuild
# Lisence: MIT
# Author: stexine
#=================================================

name: Openwrt Autobuild

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - "R1S-H5.diffconfig"
  #  schedule:
  #    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get clean
          sudo wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          sudo -E apt-get -y install bc rsync u-boot-tools
          
      - name: Clone Lean's OpenWrt source code
        run: git clone --depth 1 https://github.com/coolsnowwolf/lede -b master lede

      - name: add feeds
        run: |
        cd lede
          echo "src-git lienol https://github.com/Lienol/openwrt-package" >> feeds.conf.default
          echo "src-git openclash https://github.com/vernesong/OpenClash" >> feeds.conf.default 

      - name: Custom Applications, copy smartdns manually 
        run: |
          cd lede/package
          git clone https://github.com/Baozisoftware/luci-app-koolproxy
          git clone https://github.com/rufengsuixing/luci-app-adguardhome.git
          git clone https://github.com/stexine/openwrt-extra.git

      - name: Update and install feeds
        run: |
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load custom configuration, or just copy the working .config file
        env:
          CONFIG_FILE: "R1S-H5.diffconfig"
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE lede/.config
          cd lede
          make defconfig
        
      - name: Download package
        if: always()
        run: |
          cd lede
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          
      - name: Build
        if: always()
        run: |
          cd lede
          echo "Start building..."
          make -j$(nproc) V=s
          
          
      - name : Upload artifact
        uses: actions/upload-artifact@master
          with:
            name: OpenWrt
            path: lede/bin
          